local shell = require("shell")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/action.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/config.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/database.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/gps.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/posUtil.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/scanner.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/signal.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/autoStat.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/autoCrossbreed.lua")
shell.execute("wget https://raw.githubusercontent.com/xyqyear/auto-crossbreeding/main/autoSpread.lua")
